### try-catch

```js
try{
// 测试代码块
}catch(e){
// 错误处理代码块, 如果有错会执行的代码块
}finally{
// 最终执行代码块, 无论如何都会执行的代码块
}
```

1. 可以只用try-catch, 不用finally
2. 可以通过`throw`关键词主动抛出错误, throw后面可以抛出任意类型的对象(建议抛出Error类型)

### Error对象

每当出现错误`catch`都会接收到`Error`对象, 并执行操作

> 上面示例代码中的e就是就是Error对象

### 错误传播

错误会一直沿着函数调用链向上抛出，直到被JavaScript引擎捕获，代码终止执行。所以可以在合适的地方放置少量捕获即可.